// 從今天起，三個月的預約時段
export const calssData = [
  {
    year: "2023",
    month: "March",
    date: "29", // 年月日
    weekDay: "三", // 星期幾
    hours: [
      { time: "00:00", available: false },
      { time: "01:00", available: false },
      { time: "02:00", available: false },
      { time: "03:00", available: false },
      { time: "04:00", available: false },
      { time: "05:00", available: false },
      { time: "06:00", available: false },
      { time: "07:00", available: false },
      { time: "08:00", available: false },
      { time: "09:00", available: false },
      { time: "10:00", available: true },
      { time: "11:00", available: true },
      { time: "12:00", available: true },
      { time: "13:00", available: true },
      { time: "14:00", available: true },
      { time: "15:00", available: true },
      { time: "16:00", available: true },
      { time: "17:00", available: false },
      { time: "18:00", available: false },
      { time: "19:00", available: false },
      { time: "20:00", available: false },
      { time: "21:00", available: false },
      { time: "22:00", available: false },
      { time: "23:00", available: false },
    ],
  },
  {
    year: "2023",
    month: "March",
    date: "30", // 年月日
    weekDay: "四",
    hours: [
      { time: "00:00", available: false },
      { time: "01:00", available: false },
      { time: "02:00", available: false },
      { time: "03:00", available: false },
      { time: "04:00", available: false },
      { time: "05:00", available: false },
      { time: "06:00", available: false },
      { time: "07:00", available: false },
      { time: "08:00", available: false },
      { time: "09:00", available: false },
      { time: "10:00", available: true },
      { time: "11:00", available: true },
      { time: "12:00", available: true },
      { time: "13:00", available: true },
      { time: "14:00", available: true },
      { time: "15:00", available: true },
      { time: "16:00", available: true },
      { time: "17:00", available: false },
      { time: "18:00", available: false },
      { time: "19:00", available: false },
      { time: "20:00", available: false },
      { time: "21:00", available: false },
      { time: "22:00", available: false },
      { time: "23:00", available: false },
    ],
  },
  {
    year: "2023",
    month: "March",
    date: "31", // 年月日
    weekDay: "五",
    hours: [
      { time: "00:00", available: false },
      { time: "01:00", available: false },
      { time: "02:00", available: false },
      { time: "03:00", available: false },
      { time: "04:00", available: false },
      { time: "05:00", available: false },
      { time: "06:00", available: false },
      { time: "07:00", available: false },
      { time: "08:00", available: false },
      { time: "09:00", available: false },
      { time: "10:00", available: true },
      { time: "11:00", available: true },
      { time: "12:00", available: true },
      { time: "13:00", available: true },
      { time: "14:00", available: true },
      { time: "15:00", available: true },
      { time: "16:00", available: true },
      { time: "17:00", available: false },
      { time: "18:00", available: false },
      { time: "19:00", available: false },
      { time: "20:00", available: false },
      { time: "21:00", available: false },
      { time: "22:00", available: false },
      { time: "23:00", available: false },
    ],
  },
  {
    year: "2023",
    month: "April",
    date: "01", // 年月日
    weekDay: "六",
    hours: [
      { time: "00:00", available: false },
      { time: "01:00", available: false },
      { time: "02:00", available: false },
      { time: "03:00", available: false },
      { time: "04:00", available: false },
      { time: "05:00", available: false },
      { time: "06:00", available: false },
      { time: "07:00", available: false },
      { time: "08:00", available: false },
      { time: "09:00", available: false },
      { time: "10:00", available: true },
      { time: "11:00", available: true },
      { time: "12:00", available: true },
      { time: "13:00", available: true },
      { time: "14:00", available: true },
      { time: "15:00", available: true },
      { time: "16:00", available: true },
      { time: "17:00", available: false },
      { time: "18:00", available: false },
      { time: "19:00", available: false },
      { time: "20:00", available: false },
      { time: "21:00", available: false },
      { time: "22:00", available: false },
      { time: "23:00", available: false },
    ],
  },
  {
    year: "2023",
    month: "April",
    date: "02", // 年月日
    weekDay: "日",
    hours: [
      { time: "00:00", available: false },
      { time: "01:00", available: false },
      { time: "02:00", available: false },
      { time: "03:00", available: false },
      { time: "04:00", available: false },
      { time: "05:00", available: false },
      { time: "06:00", available: false },
      { time: "07:00", available: false },
      { time: "08:00", available: false },
      { time: "09:00", available: false },
      { time: "10:00", available: true },
      { time: "11:00", available: true },
      { time: "12:00", available: true },
      { time: "13:00", available: true },
      { time: "14:00", available: true },
      { time: "15:00", available: true },
      { time: "16:00", available: true },
      { time: "17:00", available: false },
      { time: "18:00", available: false },
      { time: "19:00", available: false },
      { time: "20:00", available: false },
      { time: "21:00", available: false },
      { time: "22:00", available: false },
      { time: "23:00", available: false },
    ],
  },
  {
    year: "2023",
    month: "April",
    date: "03", // 年月日
    weekDay: "一",
    hours: [
      { time: "00:00", available: false },
      { time: "01:00", available: false },
      { time: "02:00", available: false },
      { time: "03:00", available: false },
      { time: "04:00", available: false },
      { time: "05:00", available: false },
      { time: "06:00", available: false },
      { time: "07:00", available: false },
      { time: "08:00", available: false },
      { time: "09:00", available: false },
      { time: "10:00", available: true },
      { time: "11:00", available: true },
      { time: "12:00", available: true },
      { time: "13:00", available: true },
      { time: "14:00", available: true },
      { time: "15:00", available: true },
      { time: "16:00", available: true },
      { time: "17:00", available: false },
      { time: "18:00", available: false },
      { time: "19:00", available: false },
      { time: "20:00", available: false },
      { time: "21:00", available: false },
      { time: "22:00", available: false },
      { time: "23:00", available: false },
    ],
  },
  {
    year: "2023",
    month: "April",
    date: "04", // 年月日
    weekDay: "二",
    hours: [
      { time: "00:00", available: false },
      { time: "01:00", available: false },
      { time: "02:00", available: false },
      { time: "03:00", available: false },
      { time: "04:00", available: false },
      { time: "05:00", available: false },
      { time: "06:00", available: false },
      { time: "07:00", available: false },
      { time: "08:00", available: false },
      { time: "09:00", available: false },
      { time: "10:00", available: true },
      { time: "11:00", available: true },
      { time: "12:00", available: true },
      { time: "13:00", available: true },
      { time: "14:00", available: true },
      { time: "15:00", available: true },
      { time: "16:00", available: true },
      { time: "17:00", available: false },
      { time: "18:00", available: false },
      { time: "19:00", available: false },
      { time: "20:00", available: false },
      { time: "21:00", available: false },
      { time: "22:00", available: false },
      { time: "23:00", available: false },
    ],
  },
  {
    year: "2023",
    month: "April",
    date: "05", // 年月日
    weekDay: "三",
    hours: [
      { time: "00:00", available: false },
      { time: "01:00", available: false },
      { time: "02:00", available: false },
      { time: "03:00", available: false },
      { time: "04:00", available: false },
      { time: "05:00", available: false },
      { time: "06:00", available: false },
      { time: "07:00", available: false },
      { time: "08:00", available: false },
      { time: "09:00", available: false },
      { time: "10:00", available: true },
      { time: "11:00", available: true },
      { time: "12:00", available: true },
      { time: "13:00", available: true },
      { time: "14:00", available: true },
      { time: "15:00", available: true },
      { time: "16:00", available: true },
      { time: "17:00", available: false },
      { time: "18:00", available: false },
      { time: "19:00", available: false },
      { time: "20:00", available: false },
      { time: "21:00", available: false },
      { time: "22:00", available: false },
      { time: "23:00", available: false },
    ],
  },
];
